// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import AppShell from "@/components/AppShell";
import ThemeProvider from "@/components/ThemeProvider";
import { WalletProvider } from "@/hooks/useWallet";

export const metadata: Metadata = {
  title: "DeFi Dashboard",
  description: "AI-powered DeFi portfolio and recommendations",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative text-gray-100 font-inter min-h-screen flex overflow-hidden">
        {/* 🌌 Animated Aurora Background */}
        <div className="aurora-bg"></div>

        {/* 🧱 App Content Layer */}
        <ThemeProvider>
          <WalletProvider>
            <div className="relative flex-1 flex flex-col min-h-screen overflow-hidden z-10">
              <AppShell>{children}</AppShell>
            </div>
          </WalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}



// // src/app/layout.tsx
// import type { Metadata } from "next";
// import "./globals.css";
// import AppShell from "@/components/AppShell";
// import ThemeProvider from "@/components/ThemeProvider";

// export const metadata: Metadata = {
//   title: "DeFi Dashboard",
//   description: "AI-powered DeFi portfolio and recommendations",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className="relative text-gray-100 font-inter min-h-screen flex overflow-hidden">
//         {/* 🌌 Animated Aurora Background */}
//         <div className="aurora-bg"></div>

//         {/* 🧱 App Content Layer */}
//         <ThemeProvider>
//           <div className="relative flex-1 flex flex-col min-h-screen overflow-hidden z-10">
//             <AppShell>{children}</AppShell>
//           </div>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



// // src/app/layout.tsx
// import type { Metadata } from "next";
// import "./globals.css";
// import AppShell from "@/components/AppShell";

// export const metadata: Metadata = {
//   title: "DeFi Dashboard",
//   description: "AI-powered DeFi portfolio and recommendations",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="relative text-gray-100 font-inter min-h-screen flex overflow-hidden">
//         {/* 🌌 Animated Aurora Background */}
//         <div className="aurora-bg"></div>

//         {/* 🧱 App Content Layer */}
//         <div className="relative flex-1 flex flex-col min-h-screen overflow-hidden z-10">
//           <AppShell>{children}</AppShell>
//         </div>
//       </body>
//     </html>
//   );
// }



// // src/app/layout.tsx
// import type { Metadata } from "next";
// import "./globals.css";
// import AppShell from "@/components/AppShell";

// export const metadata: Metadata = {
//   title: "DeFi Dashboard",
//   description: "AI-powered DeFi portfolio and recommendations",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <AppShell>{children}</AppShell>
//       </body>
//     </html>
//   );
// }



// import type { Metadata } from "next";
// import "./globals.css";
// import Sidebar from "@/components/Sidebar";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";

// export const metadata: Metadata = {
//   title: "Stacks DeFi Recommender",
//   description: "Discover optimized DeFi strategies powered by AI",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="bg-gradient-to-br from-[#0a0a0d] via-[#0f0f13] to-[#17171c] text-gray-100 font-inter min-h-screen flex">
//         {/* Sidebar */}
//         <Sidebar />

//         {/* Main content area */}
//         <div className="flex-1 flex flex-col min-h-screen overflow-hidden">
//           <Header />
//           <main className="flex-1 overflow-y-auto p-6 md:p-10">{children}</main>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }




// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body className={`${geistSans.variable} ${geistMono.variable} bg-black text-white`}>
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
